#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Sep 21 17:29:10 CEST 2024
# SW Build 5094488 on Fri Jun 14 08:57:50 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim riscv_core_tb_behav -key {Behavioral:sim_1:Functional:riscv_core_tb} -tclbatch riscv_core_tb.tcl -log simulate.log"
xsim riscv_core_tb_behav -key {Behavioral:sim_1:Functional:riscv_core_tb} -tclbatch riscv_core_tb.tcl -log simulate.log

